name: 'gbfs_bike_monitoring'
version: '1.0.0'
config-version: 2

profile: 'gbfs_bike_monitoring'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  gbfs_bike_monitoring:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
